config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :bikes, only: [:create]

  root "welcome#index"

  resources :twitter_accounts, only: [:show, :update, :index, :destroy]
end

app/views/layouts/_flash_messages.html.haml
- flash.each do |type, message|
  %div{:class => "alert #{bootstrap_class_for(type)} fade in"}
    %button.close{"data-dismiss" => "alert"} ×
    = message

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-static-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{ type: "button", data: {toggle: "collapse", target: "#headernav"}}
        %span.sr-only
          Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{ href: root_url}
        Stolen Tweetor
    .collapse.navbar-collapse#headernav
      - if current_user.present?
        %p.navbar-text.navbar-right
          Signed in as
          = link_to "@#{current_user.screen_name}", current_user.twitter_url, class: "navbar-link"
          \|
          %small
            = link_to "Sign out", destroy_user_session_path, method: :delete, class: "navbar-link"
        - if current_user.is_admin
          = link_to "Admin", twitter_accounts_path, class: 'btn btn-primary navbar-btn navbar-right'
            
      - else
        .navbar-text.navbar-right
          = link_to "Sign in", omniauth_authorize_path("user", :twitter), class: 'navbar-link'
        = link_to "Connect Twitter account", omniauth_authorize_path("user", :twitter), class: 'btn btn-default navbar-btn navbar-right'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Stolen Tweetor
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %link{:href => "/fav.ico", :rel => "shortcut icon"}
  %body
    = render partial: "/layouts/header" unless @noheader
    .container-fluid.main-container
      = render partial: "/layouts/flash_messages", flash: flash
      = yield